apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apiserver
spec:
  secretName: apiserver-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - apiserver
    - localhost
    - subnetes
    - subnetes.default.svc
  ipAddresses:
    - "127.0.0.1"
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
