apiVersion: v1
kind: Service
metadata:
  name: subnetes
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: apiserver
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
