apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apiserver
  namespace: apiserver-test
spec:
  secretName: apiserver-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - apiserver
    - apiserver.apiserver-test.svc.cluster.local
    - localhost
  ipAddresses:
    - "127.0.0.1"
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
