resources:
- ca/ca.issuer.yaml
- ca/ca.secret.yaml
- certs/sa-signer.cert.yaml
- certs/apiserver.cert.yaml
- certs/client.cert.yaml
- certs/parent-kubeconfig.secret.yaml
- certs/parent-certs.configmap.yaml
- postgres/deployment.yaml
- postgres/service.yaml
- apiserver/deployment.yaml
- apiserver/service.yaml
