apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: apiserver-test
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/postgres:13.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: apiserver-test
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
